name: Publish NPM

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Create release and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
        fetch-depth: 0

    - name: Setup node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Set local git config
      run: |
        git config --local user.email "joren.broekema@gmail.com"
        git config --local user.name "Joren Broekema"

    - name: Release
      run: npm run release

    - name: Build
      run: npm run build

    - name: Publish to NPM
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run publish

    - name: Push tags to GitHub
      run: git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY} --follow-tags
